# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [BTC deposit address 3GTAqqaESW7JzPTjXWi4JEFoGSst9SdZrn] [XLM Deposit address GCDBX7GTQWJFTAJCJUGV4KXJZE6Q527YRLW75GYDJ2ODSVBOXCS4W7VS - Memo 195991]

